### ISSUE TITLE
Problem in running code

### ISSUE THREAD

**Issue by bharadwajdhornala** [Xharlie/DISN#10]
Hi @Xharlie @walsvid I am trying to run the demo.py . I have installed all the libraries as mentioned in requirements.txt. My LIIB_PATH is **export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./isosurface/:./Users/dhornala.bharadwaj/Documents/DISN-master/DISN-master/isosurface/tbb/tbb2018_20180822oss/lib/intel64/gcc4.7:/opt/intel/lib/intel64:/opt/intel/mkl/lib/intel64:/usr/local/lib64:/usr/local/lib:/usr/local/cuda/lib64**

When I run this command **python -u demo/demo.py --cam_est --log_dir checkpoint/SDF_DISN --cam_log_dir cam_est/checkpoint/cam_DISN --img_feat_twostream --sdf_res 256** . I get this error
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'Resampler' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>
 [[Node: resampler/Resampler = Resampler[T=DT_FLOAT](ResizeBilinear_1, Minimum)]]
Please guide. Thanks!

**Comment by Xharlie** [comment]
Let me google for you: https://github.com/tensorflow/tensorflow/issues/13888

**Comment by bharadwajdhornala** [comment]
But this doesn't solve the issue. Is there any other way?
Thanks!

**Comment by Xharlie** [comment]
It's a common cuda libary / version / tf issue, make sure you have only one cuda version if you are a beginner. also check your nvcc/ bashrc include path, etc.   you will encounter the same problem when running some other code as well. Here we only address DISN related issue.

**Comment by JohnG0024** [comment]
Got it to run with command `python -u demo/demo.py --cam_est --log_dir checkpoint/SDF_DISN --cam_log_dir cam_est/checkpoint/cam_DISN --img_feat_twostream --sdf_res 256`, but I'm getting an error writing to .obj. 
```
submit create_obj
command: ./isosurface/computeMarchingCubes ./demo/result.dist ./demo/result.obj -i 0.0
./isosurface/computeMarchingCubes: error while loading shared libraries: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory
command: rm -rf ./demo/result.dist
```

Is it saying I need to get this `libmkl_intel_lp64.so` file to my machine and add the path to `LIB_PATH` ?

**Comment by JohnG0024** [comment]
@Xharlie I installed MKL from Parralle Studio XE  2020 (non-root) and initialized it, installed Cuda too, modified the paths in LIB_PATH to `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./isosurface/:/media/jun/D692E99492E9797F/Users/junew/Downloads/DISN-master/isosurface/tbb/tbb2018_20180822oss/lib/intel64/gcc4.7:/home/jun/intel/lib/intel64:/home/jun/intel/mkl/lib/intel64:/home/jun/intel/intelpython3/lib:/home/jun/intel/compilers_and_libraries_2020.2.254/linux/mkl/lib/intel64_lin:/usr/local/lib:/usr/local/cuda/lib64` 

But somehow I'm still getting an error when executing the demo.py:
```
submit create_obj
command: ./isosurface/computeMarchingCubes ./demo/result.dist ./demo/result.obj -i 0.0
./isosurface/computeMarchingCubes: error while loading shared libraries: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory
command: rm -rf ./demo/result.dist
```

The `libmkl_intel_lp64.so` it says it can't find is in the ` /home/jun/intel/mkl/lib/intel64` which is listed in the `LIB_PATH` already. I don't know why it keeps saying it can't find it. Any idea how it's searching for the dependencies or what am I missing?

**Comment by JohnG0024** [comment]
@Xharlie I installed MKL from Parralle Studio XE  2020 (non-root) and initialized it, installed Cuda too, modified the paths in LIB_PATH to `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./isosurface/:/media/jun/D692E99492E9797F/Users/junew/Downloads/DISN-master/isosurface/tbb/tbb2018_20180822oss/lib/intel64/gcc4.7:/home/jun/intel/lib/intel64:/home/jun/intel/mkl/lib/intel64:/home/jun/intel/intelpython3/lib:/home/jun/intel/compilers_and_libraries_2020.2.254/linux/mkl/lib/intel64_lin:/usr/local/lib:/usr/local/cuda/lib64` 

But somehow I'm still getting an error when executing the demo.py:
```
submit create_obj
command: ./isosurface/computeMarchingCubes ./demo/result.dist ./demo/result.obj -i 0.0
./isosurface/computeMarchingCubes: error while loading shared libraries: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory
command: rm -rf ./demo/result.dist
```

The `libmkl_intel_lp64.so` it says it can't find is in the ` /home/jun/intel/mkl/lib/intel64` which is listed in the `LIB_PATH` already. I don't know why it keeps saying it can't find it. Any idea how it's searching for the dependencies or what am I missing?

**Comment by JohnG0024** [comment]
Hello, I'm getting an error when running **source isosurface/LIB_PATH
python -u preprocessing/create_point_sdf_grid.py --thread_num 9 --category all** Any idea what's the cause?

```
command: source ./isosurface/LIB_PATH
sh: 1: source: not found

...
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/jun/anaconda3/envs/tf_1.13.0/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/jun/anaconda3/envs/tf_1.13.0/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/jun/anaconda3/envs/tf_1.13.0/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/jun/anaconda3/envs/tf_1.13.0/lib/python3.6/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/home/jun/anaconda3/envs/tf_1.13.0/lib/python3.6/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "preprocessing/create_point_sdf_grid.py", line 221, in create_sdf_obj
    obj=obj.rstrip('\r\n')
  File "preprocessing/create_point_sdf_grid.py", line 221, in create_sdf_obj
    obj=obj.rstrip('\r\n')
  File "/home/jun/anaconda3/envs/tf_1.13.0/lib/python3.6/bdb.py", line 51, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/jun/anaconda3/envs/tf_1.13.0/lib/python3.6/bdb.py", line 69, in dispatch_line
    self.user_line(frame)
  File "/home/jun/anaconda3/envs/tf_1.13.0/lib/python3.6/pdb.py", line 261, in user_line
    self.interaction(frame, None)
  File "/home/jun/anaconda3/envs/tf_1.13.0/lib/python3.6/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/home/jun/anaconda3/envs/tf_1.13.0/lib/python3.6/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/home/jun/anaconda3/envs/tf_1.13.0/lib/python3.6/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
RuntimeError: input(): lost sys.stdin
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocessing/create_point_sdf_grid.py", line 342, in <module>
    lst_dir, 0.003, 16384, ish5=True, normalize=True, g=0.00, version=1, skip_all_exist=True)
  File "preprocessing/create_point_sdf_grid.py", line 322, in create_sdf
    bandwidth_lst, max_verts_lst,cat_id_lst, g_lst, version_lst,skip_all_exist_lst))
  File "/home/jun/anaconda3/envs/tf_1.13.0/lib/python3.6/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/home/jun/anaconda3/envs/tf_1.13.0/lib/python3.6/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/jun/anaconda3/envs/tf_1.13.0/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/jun/anaconda3/envs/tf_1.13.0/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/jun/anaconda3/envs/tf_1.13.0/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
RuntimeError: input(): lost sys.stdin

```
